version: "3"
services:
  customer-db:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=customers
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=bengt
      - MYSQL_PASSWORD=bengt
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - networkalex

  customer-service:
    build:
      context: ./customer/customer.service
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - networkalex

networks:
  networkalex:
    driver: bridge
