version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maria-db
    ports:
      - "3306:3306"
    networks:
      - networkalex
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "exit"]
      interval: 20s # kommer slänga första health_check efter 20 sec, kan jag anv cmd shell i den -> exit cmd
      timeout: 30s

  customer-service:
    build:
      context: ./customer/customer.service
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy # kommer köras såfort vi får godkänd health_check från db
    container_name: customer-service
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MARIA_HOST=maria-db:3306/customers
    networks:
      - networkalex

  order-service:
    build:
      context: ./order/order.service
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    container_name: order-service
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MARIA_HOST=maria-db:3306/orders
    ports:
      - "8081:8080"
    networks:
      - networkalex

  item-serivce:
    build:
      context: ./item/item.service
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    container_name: item-service
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MARIA_HOST=maria-db:3306/items
    ports:
      - "8082:8080"
    networks:
      - networkalex

  springbot-service:
    build:
      context: ./springbot
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    container_name: springbot-service
    environment:
      - token=${token}
      - openaiurl=${openaiurl}
      - openaimodel=${openaimodel}
    ports:
      - "8085:8080"
    networks:
      - networkalex

networks:
  networkalex:
    driver: bridge
## https://stackoverflow.com/questions/68186759/docker-compose-healthcheck-options
## Interval
## The health check will first run interval seconds after the container is started, and then again interval seconds after each previous check completes.

## Timeout
## If a single run of the check takes longer than timeout seconds then the check is considered to have failed.

## Retries
## It takes retries consecutive failures of the health check for the container to be considered unhealthy.
