version: '3'
services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      - MYSQL_DATABASE=customers
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=bengt
      - MYSQL_PASSWORD=bengt
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - networkalex

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - networkalex

networks:
  networkalex: